services:
  - type: web
    name: backend-project
    runtime: node
    repo: https://github.com/akunsamtiga/MarketplaceBE1.git
    branch: main
    buildCommand: npm install && npx prisma migrate deploy
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://marketplace-fe1.vercel.app
